apiVersion: v1
kind: Service
metadata:
  name: {{ include "star-warehouse-ai.fullname" . }}
  labels:
    {{- include "star-warehouse-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "star-warehouse-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
