"""Add feedback category, agent_type, confidence_score fields

Revision ID: 3a9f8e7b2c1d
Revises: 053eaa2f0a66
Create Date: 2026-04-23 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3a9f8e7b2c1d'
down_revision: Union[str, None] = '053eaa2f0a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_feedbacks', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('message_feedbacks', sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('message_feedbacks', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_message_feedbacks_agent_type'), 'message_feedbacks', ['agent_type'], unique=False)
    op.create_index(op.f('ix_message_feedbacks_category'), 'message_feedbacks', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_feedbacks_category'), table_name='message_feedbacks')
    op.drop_index(op.f('ix_message_feedbacks_agent_type'), table_name='message_feedbacks')
    op.drop_column('message_feedbacks', 'confidence_score')
    op.drop_column('message_feedbacks', 'agent_type')
    op.drop_column('message_feedbacks', 'category')
    # ### end Alembic commands ###
