"""Add phase3 review queue and token tracking models

Revision ID: c61a28a53622
Revises: a8f5311841e9
Create Date: 2026-04-24 00:20:39.668532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c61a28a53622'
down_revision: Union[str, None] = 'a8f5311841e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adversarial_test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('passed_cases', sa.Integer(), nullable=False),
    sa.Column('failed_cases', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('category_breakdown', sa.JSON(), nullable=True),
    sa.Column('severity_breakdown', sa.JSON(), nullable=True),
    sa.Column('report_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adversarial_test_runs_run_date'), 'adversarial_test_runs', ['run_date'], unique=False)
    op.create_table('pii_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('detection_types', sa.JSON(), nullable=False),
    sa.Column('redaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_audit_logs_thread_id'), 'pii_audit_logs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_pii_audit_logs_user_id'), 'pii_audit_logs', ['user_id'], unique=False)
    op.create_table('optimization_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('suggestion_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_suggestions_thread_id'), 'optimization_suggestions', ['thread_id'], unique=False)
    op.create_index(op.f('ix_optimization_suggestions_user_id'), 'optimization_suggestions', ['user_id'], unique=False)
    op.create_table('review_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_action', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('resolution_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewer_accuracy', sa.Float(), nullable=True),
    sa.Column('last_messages', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('transfer_reason', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tickets_assigned_to'), 'review_tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_review_tickets_conversation_id'), 'review_tickets', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_review_tickets_user_id'), 'review_tickets', ['user_id'], unique=False)
    op.create_table('reviewer_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_tickets', sa.Integer(), nullable=False),
    sa.Column('avg_handling_time_minutes', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('sla_compliance_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewer_metrics_reviewer_id'), 'reviewer_metrics', ['reviewer_id'], unique=False)
    op.create_table('shadow_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('production_intent', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('shadow_intent', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('intent_match', sa.Boolean(), nullable=False),
    sa.Column('production_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shadow_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jaccard_similarity', sa.Float(), nullable=False),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('llm_quality_score', sa.Float(), nullable=True),
    sa.Column('production_latency_ms', sa.Integer(), nullable=True),
    sa.Column('shadow_latency_ms', sa.Integer(), nullable=True),
    sa.Column('latency_delta_ms', sa.Integer(), nullable=True),
    sa.Column('latency_regression', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_test_results_thread_id'), 'shadow_test_results', ['thread_id'], unique=False)
    op.create_index(op.f('ix_shadow_test_results_user_id'), 'shadow_test_results', ['user_id'], unique=False)
    op.create_table('token_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('query_text', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_logs_thread_id'), 'token_usage_logs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_token_usage_logs_user_id'), 'token_usage_logs', ['user_id'], unique=False)
    op.add_column('graph_execution_logs', sa.Column('query', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graph_execution_logs', 'query')
    op.drop_index(op.f('ix_token_usage_logs_user_id'), table_name='token_usage_logs')
    op.drop_index(op.f('ix_token_usage_logs_thread_id'), table_name='token_usage_logs')
    op.drop_table('token_usage_logs')
    op.drop_index(op.f('ix_shadow_test_results_user_id'), table_name='shadow_test_results')
    op.drop_index(op.f('ix_shadow_test_results_thread_id'), table_name='shadow_test_results')
    op.drop_table('shadow_test_results')
    op.drop_index(op.f('ix_reviewer_metrics_reviewer_id'), table_name='reviewer_metrics')
    op.drop_table('reviewer_metrics')
    op.drop_index(op.f('ix_review_tickets_user_id'), table_name='review_tickets')
    op.drop_index(op.f('ix_review_tickets_conversation_id'), table_name='review_tickets')
    op.drop_index(op.f('ix_review_tickets_assigned_to'), table_name='review_tickets')
    op.drop_table('review_tickets')
    op.drop_index(op.f('ix_optimization_suggestions_user_id'), table_name='optimization_suggestions')
    op.drop_index(op.f('ix_optimization_suggestions_thread_id'), table_name='optimization_suggestions')
    op.drop_table('optimization_suggestions')
    op.drop_index(op.f('ix_pii_audit_logs_user_id'), table_name='pii_audit_logs')
    op.drop_index(op.f('ix_pii_audit_logs_thread_id'), table_name='pii_audit_logs')
    op.drop_table('pii_audit_logs')
    op.drop_index(op.f('ix_adversarial_test_runs_run_date'), table_name='adversarial_test_runs')
    op.drop_table('adversarial_test_runs')
    # ### end Alembic commands ###
